spring:
  application:
   name: antifraud

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: ${apps.kafka.groupId}

app:
  kafka:
    consumerId: ${GROUP_ID_ANTIFRAUD}
    server: ${KAFKA_SERVER}
    trustDeserializer: ${TRUST_PACKAGES_ANTIFRAUD}
    mappingNewAntiFraud: ${NEW_ANTIFRAUD}
    newPaymentTopic: ${TOPIC_PAYMENT_REQUESTED}

